import {ApiProvider} from '@emran/Context/APIContext';
import localFont from 'next/font/local';
import '.././globals.css';

const geistSans = localFont({
  src: '.././fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '.././fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Emddad English Aid',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <head>
        <title>Emddad English Aid</title>
        <meta charSet='utf-8' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, shrink-to-fit=no'
        />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://api.fontshare.com/v2/css?f[]=clash-grotesk@400,300,500&amp;display=swap'
          rel='stylesheet'
        />
        <script
          src='https://cdn.jsdelivr.net/npm/alpinejs@3.13.3/dist/cdn.min.js'
          defer='defer'></script>
      </head>
      <body>
        <ApiProvider>{children}</ApiProvider>
      </body>
    </html>
  );
}
